admin:   #超级管理员id
  emails: 2992444015@qq.com
dev: false   #是否是开发环境
log:
  root:
    level: debug   #log等级为Debug
project:
  folder: D:/webser/web_app/easypan/   #项目目录
qq:
  app:
    id: 12333
    key: 2222222
  url:
    access:
      token: https://graph.qq.com/oauth2.0/token?grant_type=authorization_code&client_id=%s&client_secret=%s&code=%s&redirect_uri=%s
    authorization: https://graph.qq.com/oauth2.0/authorize?response_type=code&client_id=%s&redirect_uri=%s&state=%s
    openid: https://graph.qq.com/oauth2.0/me?access_token=%S
    redirect: http://easypan.wuhancoder.com/qqlogincalback
    user:
      info: https://graph.qq.com/user/get_user_info?access_token=%s&oauth_consumer_key=%s&openid=%s
server:
  port: 7090  #应用服务WEB访问端口
  servlet:
    context-path: /api
    session:
      timeout: PT60M  #设置session过期时间为一个小时
spring:   #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 180000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: HikariCPDatasource
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/easypan?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
  mail:   #发送邮件配置相关
    default-encoding: UTF-8   #配置默认编码
    host: smtp.qq.com  #配置邮件服务器地址
    password: unrvrkoaqybihdai    #配置用户的密码
    port: 465   #配置邮件服务器的端口
    properties:
      mail:
        debug: true
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory   #SSL连接配置
    username: 2049202280@qq.com   #配置用户账号
  mvc:
    favicon:
      enable: false  #处理favicon
    throw-exception-if-no-handler-found: true  #处理异常
  redis:   #redis配置
    database: 0   #redis数据库索引，默认为0
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 20   #连接池最大连接数，（使用负数表示没有限制）
        max-idle: 10    #连接池最大空闲连接数
        max-wait: -1  #连接池最大阻塞的带时间  （使用负数表示没有限制）
        min-idle: 0   #连接池最小空闲连接数
    port: 6379
    timeout: 2000   #连接超时时间
  web:
    resources:
      add-mappings: false  #处理异常
  devtools:
    restart:
      exclude: static/**  #设置static目录下的所有文件不参与热部署
